### ISSUE TITLE
Route [user] not defined.

### ISSUE THREAD

**Issue by mohit0806** [KalimeroMK/LaravelEcomm#10]
@KalimeroMK  After registering a new user it's the error that 'user' route is not defined
![route-user](https://github.com/KalimeroMK/LaravelEcomm/assets/95080286/71ffb0cf-18a4-47f8-9df7-b409cd201985)

**Comment by KalimeroMK** [comment]
fix :)
@mohit0806

**Comment by mohit0806** [comment]
@KalimeroMK It's still here issue is not fixed

**Comment by KalimeroMK** [comment]
it is working on my side pls run php artisan optimize:clear
php artisan route:list  @mohit0806
