### ISSUE TITLE
issue: 'NoNodesAvailableException' in Elasticsearch during Laravel seeding 

### ISSUE THREAD

**Issue by swapnilbadgujar132** [KalimeroMK/LaravelEcomm#14]
Description:
When running php artisan migrate:fresh --seed in my Laravel application, I encountered an exception related to Elasticsearch: NoNodesAvailableException: No alive nodes found in your cluster. This exception occurs during the seeding process and prevents the seeder from completing successfully.

Steps to Reproduce:
Run the command php artisan migrate:fresh --seed in the Laravel project directory.
Observe the migration and seeding process.
The issue occurs during the seeding phase when the application attempts to interact with Elasticsearch.

![1](https://github.com/user-attachments/assets/cac1df4d-5d54-4a6f-8030-5df68cf2818d)

Expected Behavior:
The seeding process should complete successfully without errors, ensuring that all data is seeded into the database and any necessary interactions with Elasticsearch are handled correctly.

**Comment by KalimeroMK** [comment]
@swapnilbadgujar132 it mins elestic search container is not running on you local machine

**Comment by swapnilbadgujar132** [comment]
how to solve

**Comment by KalimeroMK** [comment]
@swapnilbadgujar132 run 
docker composer up -d command in root of the project and if will start all docker containers
