### ISSUE TITLE
Error in file `Modules/Message/Database/Factories/MessageFactory.php`

### ISSUE THREAD

**Issue by LeftPinkie** [KalimeroMK/LaravelEcomm#7]
There is an error in file `Modules/Message/Database/Factories/MessageFactory.php`. The `read_at` column takes a timestamp, not time. So it should be:
```
'read_at' => \Carbon\Carbon::now(), // $this->faker->time,
```

**Comment by KalimeroMK** [comment]
@LeftPinkie ty done
