### ISSUE TITLE
$recentProducts variable is not defined

### ISSUE THREAD

**Issue by mohit0806** [KalimeroMK/LaravelEcomm#9]
on the  `/product-grids` url it show that $recentProducts variable is not defined
![issue](https://github.com/KalimeroMK/LaravelEcomm/assets/95080286/af3f7daa-b5de-49b0-b94a-2dd3d4e8452b)

**Comment by KalimeroMK** [comment]
it is fix ty @mohit0806

**Comment by mohit0806** [comment]
@KalimeroMK Thanx and can you tell where are the front end routes I know it  sound stupid but I can't find them in project

**Comment by mohit0806** [comment]
@KalimeroMK Thanx
